# Generated by Django 4.2.7 on 2024-05-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_date",
            field=models.DateTimeField(default=1),
        ),
    ]
