# Generated by Django 4.2.7 on 2024-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_project_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Completed", "Completed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
