# Generated by Django 4.2.7 on 2024-05-08 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_todo_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="status",
        ),
    ]
