# Generated by Django 4.2.7 on 2024-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_remove_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
